version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:8.3.2022.22.22.43"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev