version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:22.3.2022.21.51.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev