version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:10.3.2022.7.36.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev