version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:9.3.2022.0.56.10"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev