version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:25.3.2022.17.55.55"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev