version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:11.3.2022.7.9.38"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev