version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:5.4.2022.4.12.53"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev