version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:21.3.2022.18.49.19"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev