version: "3.8"
services:
  backend:
    image: "rafameirel/springboot-react-fullstack:16.3.2022.17.49.43"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev